### ISSUE TITLE
Gọi thành công nhưng lại trả mã lỗi là thất bại.

### ISSUE THREAD

**Issue by tungchem1607** [nguyenanhung/requests#46]
Row: 842

// Response
                if (isset($curl->error) && $curl->error != false) {
                    // Debug
                    $this->logger->debug(__FUNCTION__, 'Full Data Curl Message and Http Message: ', $error_code);
                    if ($this->errorResponseIsData === TRUE) {
                        $this->logger->debug(__FUNCTION__, 'Return Error Response is Array Data');
                        $response = $error_code;
                    } elseif ($this->errorResponseIsNull === TRUE) {
                        $this->logger->debug(__FUNCTION__, 'Return Error Response is Null');
                        $response = NULL;
                    } else {
                        $errMsg   = isset($curl->errorMessage) ? $curl->errorMessage : (isset($curl->error_message) ? $curl->error_message : NULL);
                        $response = "cURL Error: " . $errMsg;
                        $this->logger->debug(__FUNCTION__, 'Return Error Response is Message: ' . $response);
                    }
                } else {
                    $response = isset($curl->rawResponse) ? $curl->rawResponse : (isset($curl->response) ? $curl->response : NULL);
                    $this->logger->debug(__FUNCTION__, 'Response from Request, no Error: ' . $response);
                }

**Comment by nguyenanhung** [comment]
Ko hiểu có lỗi ở đâu :))

**Comment by tungchem1607** [comment]
Dạ, em check gửi request thì gửi thành công nhưng lại báo về là không gửi được.
Hiện tại nó đang để là: if (isset($curl->error)) {

Em sửa thành  if (isset($curl->error) && $curl->error != false) {
Thì sẽ được ạ. Vì khi gửi thành công thì cái curl->error nó vẫn có nhưng mà bằng false ạ.

**Comment by nguyenanhung** [comment]
Đã fix
